spring :
    application :
        name : render-demo

    datasource:
        url : jdbc:h2:mem:testdb
        driverClassName : org.h2.Driver
        username : user
        password : password
    jpa : 
        database-platform : org.hibernate.dialect.H2Dialect
        defer-datasource-initialization : true
        hibernate.ddl-auto : create
    sql :
        init.mode : always
    h2.console.enabled : true

server.port : 8081
